name: Fetch YouTube Trending

on:
  workflow_dispatch: # Run manually
  schedule:
    - cron: "0 * * * *" # Every hour

jobs:
  fetch-trending:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch YouTube trending videos
        run: |
          node <<'EOF'
          const axios = require('axios');

          const API_KEY = process.env.YOUTUBE_API_KEY;
          const URL = `https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=KR&maxResults=40&key=${API_KEY}`;

          axios.get(URL)
            .then(res => {
              console.log("Trending videos:");
              res.data.items.forEach((item, index) => {
                console.log(`${index + 1}. ${item.snippet.title} (https://youtu.be/${item.id})`);
              });
            })
            .catch(err => console.error(err.response?.data || err));
          EOF
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
